AWSTemplateFormatVersion: '2010-09-09'

Description: 'AWS CloudFormation template for the Security Baseline Workshop'

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: 'General Parameters'
        Parameters:
          - ec2RoleName
          - lambdaRoleName
          - ecsRoleName
          - s3BucketName
          - iamUser
          - instanceType
          - ami

Parameters:
  ec2RoleName:
    Type: String
    Default: 'silaskumi_ec2_role3'

  lambdaRoleName:
    Type: String
    Default: 'silaskumi_lambda_role3'

  ecsRoleName:
    Type: String
    Default: 'silaskumi_ecs_role3'

  s3BucketName:
    Type: String
    Default: 'silaskumiweek2bucket3'

  iamUser:
    Type: String
    Default: 'silaskumi_week2_iam_user3'

  instanceType:
    Type: String
    Default: 't2.micro'

  ami:
    Type: String
    Default: 'ami-0c7191dc6b3e08b56'

Resources:


  ParameterStoreItem:
    Type: AWS::SSM::Parameter
    Properties:
      Name: '/silaskumi/week2lab/week2labparamter3'
      Type: String
      Value: "placeholder"

  SecretsManagerItem:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: 'silaskumi/week2lab/week2labsecret3'
      GenerateSecretString:
        SecretStringTemplate: '{"username": "silaskumi"}'
        GenerateStringKey: 'password'
        PasswordLength: 16
        ExcludeCharacters: '"@/\\'
        RequireEachIncludedType: true


  IamUser:
    Type: AWS::IAM::User
    DependsOn: SecretsManagerItem
    Properties:
      UserName: !Ref iamUser
      LoginProfile:
        Password: !Sub '{{resolve:secretsmanager:${SecretsManagerItem}:SecretString:password}}'
        PasswordResetRequired: true

  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref ec2RoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/AmazonS3FullAccess

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2Role

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref lambdaRoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  ECSRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref ecsRoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess

  s3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref s3BucketName

  RestrictedS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${s3BucketName}-restricted'

  Restricts3BucketAccess:
    Type: AWS::S3::BucketPolicy
    DependsOn: IamUser
    Properties:
      Bucket: !Ref s3Bucket
      PolicyDocument:
        Statement:
          - Sid: DenyPutObjectForOthers
            Action:
              - 's3:PutObject'
            Effect: Deny
            Principal: "*"
            Condition:
              StringNotEquals:
                aws:PrincipalArn: !GetAtt IamUser.Arn
            Resource: !Sub "${s3Bucket.Arn}/*"


  RestrictedBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref RestrictedS3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: DenyObjectAccessOutsideVPC
            Effect: Deny
            Principal: "*"
            Action:
              - "s3:GetObject"
              - "s3:PutObject"
              - "s3:DeleteObject"
            Resource: !Sub "${RestrictedS3Bucket.Arn}/*"
            Condition:
              StringNotEquals:
                aws:SourceVpce: !Ref GatewayEndpoint


  ParisVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: eu-west-3a
      VpcId: !Ref ParisVPC
      CidrBlock: 10.0.0.0/24
      MapPublicIpOnLaunch: true

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: eu-west-3a
      VpcId: !Ref ParisVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: false

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn: ParisVPC

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref ParisVPC
      InternetGatewayId: !Ref InternetGateway

  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NATGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt ElasticIP.AllocationId
      SubnetId: !Ref PublicSubnet

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref ParisVPC

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref ParisVPC

  RouteTrafficToIGW:
    Type: AWS::EC2::Route
    DependsOn:
      - AttachGateway
      - InternetGateway
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  RouteTrafficToNAT:
    Type: AWS::EC2::Route
    DependsOn:
      - NATGateway
      - PrivateSubnet
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGateway

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  PrivateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet
      RouteTableId: !Ref PrivateRouteTable


  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for EC2 instance
      VpcId: !Ref ParisVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ami
      InstanceType: !Ref instanceType
      SubnetId: !Ref PrivateSubnet
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      IamInstanceProfile: !Ref EC2InstanceProfile

  GatewayEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcEndpointType: Gateway
      VpcId: !Ref ParisVPC
      ServiceName: !Sub com.amazonaws.${AWS::Region}.s3
      RouteTableIds:
        - !Ref PublicRouteTable
        - !Ref PrivateRouteTable

  EndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for VPC endpoint
      VpcId: !Ref ParisVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 10.0.0.0/16

  InterfaceEndpoint:
    Type: AWS::EC2::VPCEndpoint
    DependsOn: EndpointSecurityGroup
    Properties:
      VpcEndpointType: Interface
      VpcId: !Ref ParisVPC
      SubnetIds:
        - !Ref PrivateSubnet
      SecurityGroupIds:
        - !Ref EndpointSecurityGroup
      ServiceName: !Sub com.amazonaws.${AWS::Region}.ssm
      PrivateDnsEnabled: false