template-file-path: template/resources.yml
parameters:
  lambdaRoleName: silaskumi_lambda_role2
  ecsRoleName: silaskumi_ecs_role2
  ec2RoleName: silaskumi_ec2_role2
  s3BucketName: silaskumiweek2bucket2
  instanceType: t2.micro
  iamUser: silaskumi_week2_iam_user2
  ami: ami-0c7191dc6b3e08b56
tags: {}
