template-file-path: template/resources.yml
parameters:
  lambdaRoleName: silaskumi_lambda_role
  ecsRoleName: silaskumi_ecs_role
  ec2RoleName: silaskumi_ec2_role
  s3BucketName: silaskumiweek2bucket
  instanceType: t2.micro
  iamUser: silaskumi_week2_iam_user
  ami: ami-0c7191dc6b3e08b56
tags: {}
